### PR TITLE
Buttons!

### PR DESCRIPTION
**Pull request by joliesky**
Added button code/descriptions and philosophy

### CODE REVIEW

**Comment by rdmurphy** [comment]
Looks like the `npm-debug.log` snuck in there - can you remove that?

Probably wouldn't hurt to add `*.log` to the `.gitignore` as well to catch it in the future.

**Comment by joliesky** [comment]
attempted to do what ryan said. did i do it right?

**Comment by rdmurphy** [comment]
:+1:

**Comment by brickaa** [comment]
Added a fix to the menu on this branch. Great job @joliesky

**Pull request merged**
